name: Build .NET Core

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Install dependencies
        run: dotnet restore ref
      - name: Build
        run: dotnet build ref --configuration Release --no-restore
      - name: Copy files
        run: cp src/bin/Release/**/* output
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Dropmaker
          path: output
